package com;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author donaldmears
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    // integer to handle turn count
    int turn = 2;
    //array to hold button inputs
    int buttons[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    
    //array to check each players input to check who wins
    int player1[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int player2[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    
    //method to determine if player one wins
    int player1() {
        if (player1[0] == 1 && player1[1] == 1 && player1[2] == 1) {
            return 1;
        }
        if (player1[3] == 1 && player1[4] == 1 && player1[5] == 1) {
            return 1;
        }
        if (player1[6] == 1 && player1[7] == 1 && player1[8] == 1) {
            return 1;
        }
        if (player1[0] == 1 && player1[3] == 1 && player1[6] == 1) {
            return 1;
        }
        if (player1[1] == 1 && player1[4] == 1 && player1[7] == 1) {
            return 1;
        }
        if (player1[2] == 1 && player1[5] == 1 && player1[8] == 1) {
            return 1;
        }
        if (player1[2] == 1 && player1[4] == 1 && player1[6] == 1) {
            return 1;
        }
        if (player1[0] == 1 && player1[4] == 1 && player1[8] == 1) {
            return 1;
        }
        return 0;
    }
    //method to determine in player 2 wins
    int player2() {
        if (player2[0] == 1 && player2[1] == 1 && player2[2] == 1) {
            return 1;
        }
        if (player2[3] == 1 && player2[4] == 1 && player2[5] == 1) {
            return 1;
        }
        if (player2[6] == 1 && player2[7] == 1 && player2[8] == 1) {
            return 1;
        }
        if (player2[0] == 1 && player2[3] == 1 && player2[6] == 1) {
            return 1;
        }
        if (player2[1] == 1 && player2[4] == 1 && player2[7] == 1) {
            return 1;
        }
        if (player2[2] == 1 && player2[5] == 1 && player2[8] == 1) {
            return 1;
        }
        if (player2[2] == 1 && player2[4] == 1 && player2[6] == 1) {
            return 1;
        }
        if (player2[0] == 1 && player2[4] == 1 && player2[8] == 1) {
            return 1;
        }
        return 0;
    }

    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        resetButton.setText("Play Again");
        resetButton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                resetButtonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("TIC-TAC-TOE");

        b1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(153, 153, 153))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (buttons[1] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b2.setText("X");
                buttons[1] = 1;
                player1[1] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            } else {
                turn++;
                b2.setText("O");
                buttons[1] = 1;
                player2[1] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (buttons[2] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b3.setText("X");
                buttons[2] = 1;
                player1[2] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            } else {
                turn++;
                b3.setText("O");
                buttons[2] = 1;
                player2[1] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if (buttons[4] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b5.setText("X");
                buttons[4] = 1;
                player1[4] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            } else {
                turn++;
                b5.setText("O");
                buttons[4] = 1;
                player2[4] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if (buttons[5] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b6.setText("X");
                buttons[5] = 1;
                player1[5] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            } else {
                turn++;
                b6.setText("O");
                buttons[5] = 1;
                player2[5] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (buttons[7] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b8.setText("X");
                buttons[7] = 1;
                player1[7] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            } else {
                turn++;
                b8.setText("O");
                buttons[7] = 1;
                player2[7] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if (buttons[8] == 0)
            if (turn % 2 == 0) {
                turn++;
                b9.setText("X");
                buttons[8] = 1;
                player1[8] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            } else {
                turn++;
                b9.setText("O");
                buttons[8] = 1;
                player2[8] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            }
        else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if (buttons[3] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b4.setText("X");
                buttons[3] = 1;
                player1[3] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            } else {
                turn++;
                b4.setText("O");
                buttons[3] = 1;
                player2[3] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (buttons[6] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b7.setText("X");
                buttons[6] = 1;
                player1[6] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            } else {
                turn++;
                b7.setText("O");
                buttons[6] = 1;
                player2[6] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if (buttons[0] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b1.setText("X");
                buttons[0] = 1;
                player1[0] = 1;

                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }

            } else {
                turn++;
                b1.setText("O");
                buttons[0] = 1;
                player2[0] = 1;
                
                int result1 = player1();
                int result2 = player2();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 1 wins!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player 2 wins!");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Button already used.");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void resetButtonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_resetButtonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonAncestorAdded

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
        turn = 2;
        for(int i = 0; i < buttons.length; i++){
            buttons[i] = 0;
            player1[i] = 0;
            player2[i] = 0;
        }
        JOptionPane.showMessageDialog(rootPane, "Game has reset");
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
